// WRM hardware and boot ABI constants. defs.inc mirrors these for assembly;
// tests/test_kernel.py checks their values without generating code.
let BYTE_BITS: UWord = 8
let WORD_BYTES: UWord = 4
let WORD_BITS: UWord = 32
let WORD_MASK: UWord = 0xFFFFFFFF
let INSTRUCTION_BYTES: UWord = WORD_BYTES
let GPR_COUNT: UWord = 32
let REG_RESULT: UWord = 1
let REG_SYSCALL: UWord = 9
let REG_SP: UWord = 30
let REG_RA: UWord = 31
let STACK_ALIGNMENT: UWord = 8
let STACK_ALIGN_MASK: UWord = STACK_ALIGNMENT - 1
let KERNEL_STACK_BYTES: UWord = 8192
let TRAP_DISPATCH_HEADROOM: UWord = 512
// trapBadStack's own stack: the trusted kernel stack failed its checks.
let TRAP_EMERGENCY_STACK_BYTES: UWord = 2048
let STACK_CANARY: UWord = 0x4C414958

let CR_STATUS: UWord = 0
let CR_PTBR: UWord = 6
let STATUS_IE: UWord = 1 << 0
let STATUS_PIE: UWord = 1 << 1
let STATUS_UM: UWord = 1 << 2
let STATUS_PUM: UWord = 1 << 3
let STATUS_EXL: UWord = 1 << 4
let STATUS_SS: UWord = 1 << 5
let STATUS_PSS: UWord = 1 << 6
let STATUS_TRAP_RETURN_MASK: UWord = STATUS_PIE | STATUS_PUM | STATUS_EXL | STATUS_SS | STATUS_PSS
let FCSR_NX: UWord = 1 << 0
let FCSR_ROUND_UP: UWord = 3 << 5

let CAUSE_INTERRUPT: UWord = 0
let CAUSE_ILLEGAL_INSTRUCTION: UWord = 1
let CAUSE_MISALIGNED_FETCH: UWord = 2
let CAUSE_MISALIGNED_LOAD: UWord = 3
let CAUSE_MISALIGNED_STORE: UWord = 4
let CAUSE_FETCH_BUS_ERROR: UWord = 5
let CAUSE_LOAD_BUS_ERROR: UWord = 6
let CAUSE_STORE_BUS_ERROR: UWord = 7
let CAUSE_FETCH_PAGE_FAULT: UWord = 8
let CAUSE_LOAD_PAGE_FAULT: UWord = 9
let CAUSE_STORE_PAGE_FAULT: UWord = 10
let CAUSE_PRIVILEGED_INSTRUCTION: UWord = 11
let CAUSE_SYSCALL: UWord = 12
let CAUSE_BREAKPOINT: UWord = 13
let CAUSE_SINGLE_STEP: UWord = 14
let CAUSE_DEBUG_TRIGGER: UWord = 15
let ERRNO_ENOSYS: Word = 38
let ERRNO_EINVAL: Word = 22
let ERRNO_EFAULT: Word = 14
let SYS_DEBUG_PUT_CHAR: UWord = 0
let SYS_EXIT: UWord = 1
let SYS_YIELD: UWord = 2
let ERRNO_EPERM: Word = 1
let ERRNO_ESRCH: Word = 3
let ERRNO_EBADF: Word = 9
let ERRNO_ENFILE: Word = 23
let ERRNO_EMFILE: Word = 24
let ERRNO_EPIPE: Word = 32
let SYS_HANDLE_CLOSE: UWord = 16
let SYS_HANDLE_COPY: UWord = 17
let SYS_ENDPOINT_DESTROY: UWord = 18
let SYS_IPC_SEND: UWord = 19
let SYS_IPC_RECEIVE: UWord = 20
let SYS_IPC_CALL: UWord = 21
let SYS_IPC_ACCEPT: UWord = 22
let SYS_IPC_REPLY: UWord = 23
let ERRNO_EDEADLK: Word = 35
let ERRNO_EOVERFLOW: Word = 75
let IPC_MESSAGE_MAX: UWord = 32
let ERRNO_EBUSY: Word = 16
let ERRNO_EMSGSIZE: Word = 90
let RIGHT_SEND: UWord = 1
let RIGHT_RECEIVE: UWord = 2
let RIGHT_MANAGE: UWord = 4
let RIGHT_ALL: UWord = 7
// Versioned init ABI for the first embedded service/client pair.
let DEVICE_UART_TX: UWord = 1
let START_MAGIC: UWord = 0x5449584C
let START_VERSION: UWord = 1
let START_BLOCK_BYTES: UWord = 48
let START_BLOCK_VA: UWord = 0x40002000
let START_DATA_VA: UWord = 0x40001000
let START_ROLE_SERVER: UWord = 1
let START_ROLE_CLIENT: UWord = 2
let START_PROTOCOL_UART_BYTE: UWord = 1
let START_PROTOCOL_CONSOLE: UWord = 2
let CONSOLE_VERSION: UWord = 1
let CONSOLE_WRITE: UWord = 1
let CONSOLE_RESULT: UWord = 2
let CONSOLE_HEADER_BYTES: UWord = 4
let CONSOLE_TEXT_MAX: UWord = 28
let CONSOLE_RESPONSE_BYTES: UWord = 12
let CONSOLE_REQUEST_HEADER: UWord = 257
let CONSOLE_RESPONSE_HEADER: UWord = 524801
let ERRNO_EPROTO: Word = 71
let START_FIELD_MAGIC: UWord = 0
let START_FIELD_VERSION: UWord = 4
let START_FIELD_BYTES: UWord = 8
let START_FIELD_ROLE: UWord = 12
let START_FIELD_TASK_ID: UWord = 16
let START_FIELD_ENDPOINT: UWord = 20
let START_FIELD_RIGHTS: UWord = 24
let START_FIELD_DEVICES: UWord = 28
let START_FIELD_DATA: UWord = 32
let START_FIELD_DATA_BYTES: UWord = 36
let START_FIELD_IPC_LIMIT: UWord = 40
let START_FIELD_PROTOCOL: UWord = 44
let SYSCALL_UNSUPPORTED: UWord = WORD_MASK
let PANIC_EXIT_CODE: UWord = 254

let PAGE_SHIFT: UWord = 12
let PAGE_SIZE: UWord = 1 << PAGE_SHIFT
let PAGE_MASK: UWord = PAGE_SIZE - 1
let PAGE_TABLE_ENTRIES: UWord = PAGE_SIZE / WORD_BYTES
let SUPERPAGE_SHIFT: UWord = 22
let SUPERPAGE_SIZE: UWord = 1 << SUPERPAGE_SHIFT
let PTBR_ENABLE: UWord = 1
let PTE_V: UWord = 1 << 0
let PTE_R: UWord = 1 << 1
let PTE_W: UWord = 1 << 2
let PTE_X: UWord = 1 << 3
let PTE_U: UWord = 1 << 4
let PTE_RWX_BITS: UWord = PTE_R | PTE_W | PTE_X
let PTE_RW: UWord = PTE_V | PTE_R | PTE_W
let PTE_RWX: UWord = PTE_RW | PTE_X
let PTE_RX: UWord = PTE_V | PTE_R | PTE_X
let PTE_RO: UWord = PTE_V | PTE_R
let TLBI_ALL: UWord = 2
let RAM_SLOT_COUNT: UWord = 4
let RAM_SLOT_MAX_BYTES: UWord = 32 * 1024 * 1024
let RAM_MAX_BYTES: UWord = RAM_SLOT_COUNT * RAM_SLOT_MAX_BYTES

let VRAM_BASE: UWord = 0xFC000000
let IO_BASE: UWord = 0xFD000000
let PIC_ENABLE: UWord = IO_BASE + WORD_BYTES
let PIC_CLAIM: UWord = IO_BASE + 3 * WORD_BYTES
let PIC_NO_IRQ: UWord = WORD_MASK
let PIC_LINE_COUNT: UWord = 32
let TIMER_BASE: UWord = IO_BASE + 3 * PAGE_SIZE
let TIMER_COUNT_LO: UWord = TIMER_BASE
let TIMER_COUNT_HI: UWord = TIMER_BASE + WORD_BYTES
let TIMER_FREQUENCY: UWord = TIMER_BASE + 2 * WORD_BYTES
let TIMER_RELOAD: UWord = TIMER_BASE + 3 * WORD_BYTES
let TIMER_CONTROL: UWord = TIMER_BASE + 5 * WORD_BYTES
let TIMER_STATUS: UWord = TIMER_BASE + 6 * WORD_BYTES
let TIMER_IRQ: UWord = 2
let TIMER_IRQ_MASK: UWord = 1 << TIMER_IRQ
let TIMER_ENABLE: UWord = 1
let TIMER_PERIODIC: UWord = 2
let TIMER_EXPIRED: UWord = 1
let UART_BASE: UWord = IO_BASE + 2 * PAGE_SIZE
let POWER_BASE: UWord = IO_BASE + 4 * PAGE_SIZE
let DISK0_BASE: UWord = IO_BASE + 5 * PAGE_SIZE
let DISK1_BASE: UWord = IO_BASE + 6 * PAGE_SIZE
let VIDEO_BASE: UWord = IO_BASE + 7 * PAGE_SIZE
let FLOPPY_BASE: UWord = IO_BASE + 8 * PAGE_SIZE
let RNG_BASE: UWord = IO_BASE + 14 * PAGE_SIZE
let RNG_SEEDED: UWord = 1

let BOOT_MAGIC: UWord = 0x424D5257
let BOOT_INFO_MAGIC: UWord = 0x4F464E49
let BOOT_INFO: UWord = 0x1000
let BOOT_INFO_END: UWord = BOOT_INFO + PAGE_SIZE
// Entry state at the end of the boot info page, within the signed offset(r0)
// field. Page zero stays unmapped, so a NULL access faults.
let KERNEL_SP: UWord = BOOT_INFO_END - 4 * WORD_BYTES
let KERNEL_STACK_BOTTOM: UWord = KERNEL_SP + WORD_BYTES
let KERNEL_STACK_TOP: UWord = KERNEL_STACK_BOTTOM + WORD_BYTES
let TRAP_SAVED_R1: UWord = KERNEL_STACK_TOP + WORD_BYTES
// Boot info and its device table must end below the entry state.
let BOOT_INFO_LIMIT: UWord = KERNEL_SP
let BOOT_INFO_BYTES: UWord = BOOT_INFO_LIMIT - BOOT_INFO
let BOOT_INFO_MIN_SIZE: UWord = 40
let BOOT_FIELD_MAGIC: UWord = 0
let BOOT_FIELD_SIZE: UWord = WORD_BYTES
let BOOT_FIELD_RAM_SIZE: UWord = 2 * WORD_BYTES
let BOOT_FIELD_DISK: UWord = 3 * WORD_BYTES
let BOOT_LOAD: UWord = 0x10000
let DEVICE_ENTRY_BYTES: UWord = 2 * WORD_BYTES
let SECTOR_SIZE: UWord = 512
let SECTOR_MASK: UWord = SECTOR_SIZE - 1
let DISK_PRESENT: UWord = 1 << 0
let DISK_BUSY: UWord = 1 << 2
let DISK_DONE: UWord = 1 << 3
let DISK_CHANGED: UWord = 1 << 5
let DISK_READ: UWord = 1

let SCREEN_WIDTH: UWord = 640
let SCREEN_HEIGHT: UWord = 480
let SCREEN_BPP: UWord = 8
let SCREEN_PITCH: UWord = SCREEN_WIDTH * SCREEN_BPP / BYTE_BITS
let CELL_WIDTH: UWord = 8
let GLYPH_HEIGHT: UWord = 16
let GLYPH_WIDTH: UWord = 16
let GLYPH_ROW_BYTES: UWord = GLYPH_WIDTH / BYTE_BITS
let GLYPH_BYTES: UWord = GLYPH_ROW_BYTES * GLYPH_HEIGHT
let VIDEO_BUSY: UWord = 1
let VIDEO_ENABLE: UWord = 1
let VIDEO_MODE_640_480: UWord = 1
let VIDEO_8BPP: UWord = 2 << 4
let VIDEO_XY_SHIFT: UWord = 16
let VIDEO_FILL: UWord = 1
let VIDEO_COPY: UWord = 2
let VIDEO_EXPAND: UWord = 3
let PALETTE_BLACK: UWord = 0
let PALETTE_WHITE: UWord = 0xFFFFFF
let PALETTE_BACKGROUND: UWord = 0
let PALETTE_FOREGROUND: UWord = 1

let UNICODE_MAX: UWord = 0x10FFFF
let UNICODE_SURROGATE_MIN: UWord = 0xD800
let UNICODE_SURROGATE_MAX: UWord = 0xDFFF
let UNICODE_REPLACEMENT: UWord = 0xFFFD

let HEX_DIGIT_BITS: UWord = 4
let HEX_DIGIT_MASK: UWord = (1 << HEX_DIGIT_BITS) - 1
let HEX_WORD_DIGITS: UWord = WORD_BITS / HEX_DIGIT_BITS
let HEX_TOP_SHIFT: UWord = WORD_BITS - HEX_DIGIT_BITS
let DECIMAL_BASE: UWord = 10
let ASCII_ZERO: UWord = 48
let ASCII_HEX_ALPHA_OFFSET: UWord = 55 // 'A' - 10
let ASCII_NEWLINE: UWord = 10

export {
    DEVICE_UART_TX, START_MAGIC, START_VERSION, START_BLOCK_BYTES, START_BLOCK_VA, START_DATA_VA,
    START_ROLE_SERVER, START_ROLE_CLIENT, START_PROTOCOL_UART_BYTE,
    START_PROTOCOL_CONSOLE, CONSOLE_VERSION, CONSOLE_WRITE, CONSOLE_RESULT, CONSOLE_HEADER_BYTES, CONSOLE_TEXT_MAX, CONSOLE_RESPONSE_BYTES, CONSOLE_REQUEST_HEADER, CONSOLE_RESPONSE_HEADER, ERRNO_EPROTO,
    START_FIELD_MAGIC, START_FIELD_VERSION, START_FIELD_BYTES, START_FIELD_ROLE, START_FIELD_TASK_ID,
    START_FIELD_ENDPOINT, START_FIELD_RIGHTS, START_FIELD_DEVICES, START_FIELD_DATA,
    START_FIELD_DATA_BYTES, START_FIELD_IPC_LIMIT, START_FIELD_PROTOCOL,
    BYTE_BITS, WORD_BYTES, WORD_BITS, WORD_MASK, INSTRUCTION_BYTES,
    GPR_COUNT, REG_RESULT, REG_SYSCALL, REG_SP, REG_RA, STACK_ALIGNMENT, STACK_ALIGN_MASK,
    KERNEL_STACK_BYTES, TRAP_DISPATCH_HEADROOM, TRAP_EMERGENCY_STACK_BYTES, STACK_CANARY,
    CR_STATUS, CR_PTBR, STATUS_IE, STATUS_PIE, STATUS_UM, STATUS_PUM,
    STATUS_EXL, STATUS_SS, STATUS_PSS, STATUS_TRAP_RETURN_MASK,
    FCSR_NX, FCSR_ROUND_UP,
    CAUSE_INTERRUPT, CAUSE_ILLEGAL_INSTRUCTION, CAUSE_MISALIGNED_FETCH,
    CAUSE_MISALIGNED_LOAD, CAUSE_MISALIGNED_STORE, CAUSE_FETCH_BUS_ERROR,
    CAUSE_LOAD_BUS_ERROR, CAUSE_STORE_BUS_ERROR, CAUSE_FETCH_PAGE_FAULT,
    CAUSE_LOAD_PAGE_FAULT, CAUSE_STORE_PAGE_FAULT, CAUSE_PRIVILEGED_INSTRUCTION,
    CAUSE_SYSCALL, CAUSE_BREAKPOINT, CAUSE_SINGLE_STEP, CAUSE_DEBUG_TRIGGER,
    ERRNO_ENOSYS, ERRNO_EINVAL, ERRNO_EFAULT, SYS_DEBUG_PUT_CHAR, SYS_EXIT, SYS_YIELD, ERRNO_EPERM, ERRNO_ESRCH, ERRNO_EBADF, ERRNO_ENFILE, ERRNO_EMFILE, ERRNO_EPIPE, SYS_HANDLE_CLOSE, SYS_HANDLE_COPY, SYS_ENDPOINT_DESTROY, SYS_IPC_SEND, SYS_IPC_RECEIVE, SYS_IPC_CALL, SYS_IPC_ACCEPT, SYS_IPC_REPLY, ERRNO_EDEADLK, ERRNO_EOVERFLOW, IPC_MESSAGE_MAX, ERRNO_EBUSY, ERRNO_EMSGSIZE, RIGHT_SEND, RIGHT_RECEIVE, RIGHT_MANAGE, RIGHT_ALL, SYSCALL_UNSUPPORTED, PANIC_EXIT_CODE,
    PAGE_SHIFT, PAGE_SIZE, PAGE_MASK, PAGE_TABLE_ENTRIES, SUPERPAGE_SHIFT,
    SUPERPAGE_SIZE, PTBR_ENABLE, PTE_V, PTE_R, PTE_W, PTE_X, PTE_U,
    PTE_RWX_BITS, PTE_RW, PTE_RWX, PTE_RX, PTE_RO, TLBI_ALL,
    RAM_SLOT_COUNT, RAM_SLOT_MAX_BYTES, RAM_MAX_BYTES,
    VRAM_BASE, IO_BASE, PIC_ENABLE, PIC_CLAIM, PIC_NO_IRQ, PIC_LINE_COUNT,
    TIMER_BASE, TIMER_COUNT_LO, TIMER_COUNT_HI, TIMER_FREQUENCY, TIMER_RELOAD, TIMER_CONTROL, TIMER_STATUS,
    TIMER_IRQ, TIMER_IRQ_MASK, TIMER_ENABLE, TIMER_PERIODIC, TIMER_EXPIRED,
    UART_BASE, POWER_BASE, DISK0_BASE,
    DISK1_BASE, VIDEO_BASE, FLOPPY_BASE, RNG_BASE, RNG_SEEDED,
    BOOT_MAGIC, BOOT_INFO_MAGIC, BOOT_INFO, BOOT_INFO_END, BOOT_INFO_LIMIT, BOOT_INFO_BYTES,
    KERNEL_SP, KERNEL_STACK_BOTTOM, KERNEL_STACK_TOP, TRAP_SAVED_R1,
    BOOT_INFO_MIN_SIZE, BOOT_FIELD_MAGIC, BOOT_FIELD_SIZE, BOOT_FIELD_RAM_SIZE, BOOT_FIELD_DISK,
    BOOT_LOAD, DEVICE_ENTRY_BYTES, SECTOR_SIZE, SECTOR_MASK,
    DISK_PRESENT, DISK_BUSY, DISK_DONE, DISK_CHANGED, DISK_READ,
    SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_BPP, SCREEN_PITCH, CELL_WIDTH, GLYPH_HEIGHT, GLYPH_WIDTH,
    GLYPH_ROW_BYTES, GLYPH_BYTES, VIDEO_BUSY, VIDEO_ENABLE, VIDEO_MODE_640_480,
    VIDEO_8BPP, VIDEO_XY_SHIFT, VIDEO_FILL, VIDEO_COPY, VIDEO_EXPAND,
    PALETTE_BLACK, PALETTE_WHITE, PALETTE_BACKGROUND, PALETTE_FOREGROUND,
    UNICODE_MAX, UNICODE_SURROGATE_MIN, UNICODE_SURROGATE_MAX, UNICODE_REPLACEMENT,
    HEX_DIGIT_BITS, HEX_DIGIT_MASK, HEX_WORD_DIGITS, HEX_TOP_SHIFT,
    DECIMAL_BASE, ASCII_ZERO, ASCII_HEX_ALPHA_OFFSET, ASCII_NEWLINE,
}

// Screen service ABI. DMA commands remain kernel-broker operations.
let SYS_IRQ_WAIT: UWord = 24
let SYS_IRQ_COMPLETE: UWord = 25
let SYS_SCREEN_CONTROL: UWord = 26
let SYS_FONT_BEGIN: UWord = 27
let SYS_FONT_FINISH: UWord = 28
let SYS_FONT_CANCEL: UWord = 29
let SYS_FONT_VALIDATE: UWord = 30
let ERRNO_EIO: Word = 5
let ERRNO_EAGAIN: Word = 11
let ERRNO_ETIMEDOUT: Word = 110
let DEVICE_SCREEN: UWord = 2
let DEVICE_FONT: UWord = 4
let SERVICE_START_VERSION: UWord = 2
let SERVICE_START_BYTES: UWord = 64
let START_ROLE_STORAGE: UWord = 3
let START_PROTOCOL_SCREEN: UWord = 3
let START_PROTOCOL_FONT: UWord = 4
let SERVICE_IMAGE_BASE: UWord = 0x41000000
let SERVICE_IMAGE_END: UWord = 0x41400000
let SCREEN_VRAM_VA: UWord = 0x80000000
let SCREEN_VIDEO_VA: UWord = 0x80400000
let SCREEN_FONT_VA: UWord = 0x80800000
let SCREEN_VRAM_BYTES: UWord = 640 * 480 + 8192
let VIDEO_IRQ: UWord = 5
let PIC_PENDING: UWord = IO_BASE
let FONT_GENERATION: UWord = 1
let FONT_REQUEST_HEADER: UWord = 0x000C0101
let FONT_VALIDATE_HEADER: UWord = 0x000C0301
let FONT_RESPONSE_HEADER: UWord = 0x001C0201
let SCREEN_REQUEST_HEADER: UWord = 0x00000102
let SCREEN_RESPONSE_HEADER: UWord = 0x00080202

export { SYS_IRQ_WAIT, SYS_IRQ_COMPLETE, SYS_SCREEN_CONTROL, SYS_FONT_BEGIN, SYS_FONT_FINISH, SYS_FONT_CANCEL, SYS_FONT_VALIDATE, ERRNO_EIO, ERRNO_EAGAIN, ERRNO_ETIMEDOUT, DEVICE_SCREEN, DEVICE_FONT, SERVICE_START_VERSION, SERVICE_START_BYTES, START_ROLE_STORAGE, START_PROTOCOL_SCREEN, START_PROTOCOL_FONT, SERVICE_IMAGE_BASE, SERVICE_IMAGE_END, SCREEN_VRAM_VA, SCREEN_VIDEO_VA, SCREEN_FONT_VA, SCREEN_VRAM_BYTES, VIDEO_IRQ, PIC_PENDING, FONT_GENERATION, FONT_REQUEST_HEADER, FONT_VALIDATE_HEADER, FONT_RESPONSE_HEADER, SCREEN_REQUEST_HEADER, SCREEN_RESPONSE_HEADER }

// Simple input, read-only disk and file service ABI.
let KEYBOARD_BASE: UWord = IO_BASE + PAGE_SIZE
let KEYBOARD_IRQ: UWord = 0
let DEVICE_INPUT: UWord = 8
let DEVICE_DISK: UWord = 16
let START_ROLE_INPUT: UWord = 4
let START_ROLE_DISK: UWord = 5
let START_ROLE_FILE: UWord = 6
let START_PROTOCOL_INPUT: UWord = 5
let START_PROTOCOL_DISK: UWord = 6
let START_PROTOCOL_FILE: UWord = 7
let SYS_INPUT_READ: UWord = 31
let SYS_DISK_INFO: UWord = 32
let SYS_DISK_BEGIN: UWord = 33
let SYS_DISK_FINISH: UWord = 34
let SYS_DISK_CANCEL: UWord = 35
let INPUT_REQUEST_HEADER: UWord = 0x00000101
let INPUT_RESPONSE_HEADER: UWord = 0x001C0201
let DISK_REQUEST_HEADER: UWord = 0x000C0101
let DISK_STAT_HEADER: UWord = 0x000C0301
let DISK_RESPONSE_HEADER: UWord = 0x001C0201
let FILE_REQUEST_HEADER: UWord = 0x00100101
let FILE_STAT_HEADER: UWord = 0x000C0301
let FILE_RESPONSE_HEADER: UWord = 0x001C0201
let DATA_GENERATION: UWord = 1
let FILE_FONT_ID: UWord = 1
let ERRNO_ENOENT: Word = 2

export { KEYBOARD_BASE, KEYBOARD_IRQ, DEVICE_INPUT, DEVICE_DISK, START_ROLE_INPUT, START_ROLE_DISK, START_ROLE_FILE, START_PROTOCOL_INPUT, START_PROTOCOL_DISK, START_PROTOCOL_FILE, SYS_INPUT_READ, SYS_DISK_INFO, SYS_DISK_BEGIN, SYS_DISK_FINISH, SYS_DISK_CANCEL, INPUT_REQUEST_HEADER, INPUT_RESPONSE_HEADER, DISK_REQUEST_HEADER, DISK_STAT_HEADER, DISK_RESPONSE_HEADER, FILE_REQUEST_HEADER, FILE_STAT_HEADER, FILE_RESPONSE_HEADER, DATA_GENERATION, FILE_FONT_ID, ERRNO_ENOENT }

// Runtime task ABI: separate creation capability and object management rights.
let SYS_TASK_CREATE: UWord = 36
let SYS_TASK_CONFIGURE: UWord = 37
let SYS_TASK_PUBLISH: UWord = 38
let SYS_TASK_INSPECT: UWord = 39
let SYS_TASK_TERMINATE: UWord = 40
let SYS_TASK_COLLECT: UWord = 41
let TASK_RIGHT_CONFIGURE: UWord = 1
let TASK_RIGHT_PUBLISH: UWord = 2
let TASK_RIGHT_INSPECT: UWord = 4
let TASK_RIGHT_TERMINATE: UWord = 8
let TASK_RIGHT_COLLECT: UWord = 16
let TASK_RIGHT_ALL: UWord = 31
let TASK_EVENT_FAULT: UWord = 1
let TASK_EVENT_TERMINATED: UWord = 2
let TASK_EVENT_RECLAIMED: UWord = 4
let TASK_EVENT_QUARANTINED: UWord = 8
let RUNTIME_START_MAGIC: UWord = 0x5254584C
let RUNTIME_START_VERSION: UWord = 1
let RUNTIME_START_BYTES: UWord = 40
let TASK_EVENT_BYTES: UWord = 44
export { SYS_TASK_CREATE, SYS_TASK_CONFIGURE, SYS_TASK_PUBLISH, SYS_TASK_INSPECT,
    SYS_TASK_TERMINATE, SYS_TASK_COLLECT, TASK_RIGHT_CONFIGURE, TASK_RIGHT_PUBLISH,
    TASK_RIGHT_INSPECT, TASK_RIGHT_TERMINATE, TASK_RIGHT_COLLECT, TASK_RIGHT_ALL,
    TASK_EVENT_FAULT, TASK_EVENT_TERMINATED, TASK_EVENT_RECLAIMED, TASK_EVENT_QUARANTINED,
    RUNTIME_START_MAGIC, RUNTIME_START_VERSION, RUNTIME_START_BYTES, TASK_EVENT_BYTES }

// Scoped eager-memory ABI; counts are pages except populate byte ranges.
let SYS_MEM_SPACE: UWord = 42
let SYS_MEM_ALLOC: UWord = 43
let SYS_MEM_RELEASE: UWord = 44
let SYS_MEM_MAP: UWord = 45
let SYS_MEM_UNMAP: UWord = 46
let SYS_MEM_PROTECT: UWord = 47
let SYS_MEM_POPULATE: UWord = 48
let SYS_MEM_CLOSE: UWord = 49
let MEM_RIGHT_ALLOC: UWord = 1
let MEM_RIGHT_MAP: UWord = 2
let MEM_RIGHT_UNMAP: UWord = 4
let MEM_RIGHT_PROTECT: UWord = 8
let MEM_RIGHT_POPULATE: UWord = 16
let MEM_RIGHT_ALL: UWord = 63
let MEM_REGION_PAGES: UWord = 16
let MEM_VA_START: UWord = 0x60000000
let MEM_VA_END: UWord = 0xa0000000
let ERRNO_ENOMEM: Word = 12
export { SYS_MEM_SPACE, SYS_MEM_ALLOC, SYS_MEM_RELEASE, SYS_MEM_MAP, SYS_MEM_UNMAP, SYS_MEM_PROTECT, SYS_MEM_POPULATE, SYS_MEM_CLOSE, MEM_RIGHT_ALLOC, MEM_RIGHT_MAP, MEM_RIGHT_UNMAP, MEM_RIGHT_PROTECT, MEM_RIGHT_POPULATE, MEM_RIGHT_ALL, MEM_REGION_PAGES, MEM_VA_START, MEM_VA_END, ERRNO_ENOMEM }

let SYS_MEM_GRANT: UWord = 50
let SYS_MEM_GRANT_MAP: UWord = 51
let SYS_MEM_GRANT_CLOSE: UWord = 52
let MEM_RIGHT_SHARE: UWord = 32
export { SYS_MEM_GRANT, SYS_MEM_GRANT_MAP, SYS_MEM_GRANT_CLOSE, MEM_RIGHT_SHARE }

let SYS_ENDPOINT_CREATE: UWord = 53
let SYS_TASK_DEVICES: UWord = 54
let ENDPOINT_MODE_RAW: UWord = 0
let ENDPOINT_MODE_SERVICE: UWord = 1
export { SYS_ENDPOINT_CREATE, SYS_TASK_DEVICES, ENDPOINT_MODE_RAW, ENDPOINT_MODE_SERVICE }
